# Generated by Django 3.1.3 on 2021-04-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210329_2326'),
    ]

    operations = [

    ]
