# Generated by Django 3.1.3 on 2021-06-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.BooleanField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=190, null=True),
        ),
    ]
