# Generated by Django 3.1.3 on 2021-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.BooleanField(choices=[('is_student', 'Is Student'), ('is_teacher ', 'Is Teacher')], max_length=190, null=True),
        ),
    ]
