# Generated by Django 3.1.3 on 2021-06-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
