# Generated by Django 3.1.3 on 2021-06-27 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0005_studentsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsection',
            name='level',
        ),
        migrations.AddField(
            model_name='studentsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
