# Generated by Django 3.1.3 on 2021-06-27 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Beezaccs', '0008_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Procedure', models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], max_length=190, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignmentType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Type01', to='Beezaccs.procedure')),
                ('TopicType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TypeTopic01', to='Beezaccs.topictype')),
                ('kgclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes07', to='Beezaccs.classes')),
                ('kgsubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject07', to='Beezaccs.kin_categoriesclass')),
                ('kgtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topic01', to='Beezaccs.sub_topic')),
                ('kguint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit01', to='Beezaccs.topic')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level07', to='Beezaccs.level')),
                ('mdtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topic03', to='Beezaccs.mid_topic')),
                ('mduint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit03', to='Beezaccs.mid_uint')),
                ('midclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes09', to='Beezaccs.mid_classes')),
                ('midsubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject09', to='Beezaccs.mid_subject')),
                ('prclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes08', to='Beezaccs.pr_classes')),
                ('prsubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject08', to='Beezaccs.pr_subject')),
                ('prtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topic02', to='Beezaccs.pr_topic')),
                ('pruint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit02', to='Beezaccs.pr_uint')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student07', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
