# Generated by Django 3.1.3 on 2021-06-27 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0009_studentassignment_topictype'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='DurationTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='submissionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
