# Generated by Django 3.1.3 on 2021-06-27 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Beezaccs', '0010_auto_20210627_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student07', to=settings.AUTH_USER_MODEL),
        ),
    ]
