# Generated by Django 3.1.3 on 2021-06-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0011_auto_20210627_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='Section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Section07', to='Beezaccs.section'),
        ),
    ]
