# Generated by Django 3.1.3 on 2021-07-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0013_durationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='DurationTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DurationTime07', to='Beezaccs.durationtime'),
        ),
    ]
