# Generated by Django 3.1.3 on 2021-07-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0014_auto_20210703_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='AssignmentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Type01', to='Beezaccs.procedure'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='kgtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topic01', to='Beezaccs.sub_topic'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='kguint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit01', to='Beezaccs.topic'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='mdtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topic03', to='Beezaccs.mid_topic'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='mduint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit03', to='Beezaccs.mid_uint'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='prtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topic02', to='Beezaccs.pr_topic'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='pruint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit02', to='Beezaccs.pr_uint'),
        ),
    ]
