# Generated by Django 3.1.3 on 2021-07-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0015_auto_20210704_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topictype',
            old_name='Procedure',
            new_name='TopicType',
        ),
    ]
