# Generated by Django 3.1.3 on 2021-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0016_auto_20210704_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='/', null=True, upload_to='static'),
        ),
    ]
