# Generated by Django 3.1.3 on 2021-07-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0020_auto_20210706_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsectionclasssubject',
            old_name='secionClass',
            new_name='sectionClass',
        ),
    ]
