# Generated by Django 3.1.3 on 2021-07-06 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_live'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Beezaccs', '0021_auto_20210706_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes03', to='Beezaccs.classes')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level03', to='Beezaccs.level')),
                ('midclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes05', to='Beezaccs.mid_classes')),
                ('prclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes04', to='Beezaccs.pr_classes')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student03', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Section03', to='Beezaccs.section')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student05', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgsubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject03', to='Beezaccs.kin_categoriesclass')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level06', to='Beezaccs.level')),
                ('midsubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject05', to='Beezaccs.mid_subject')),
                ('prsubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject04', to='Beezaccs.pr_subject')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student06', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentsectionclasssubject',
            name='sectionClass',
        ),
        migrations.RemoveField(
            model_name='studentsectionclasssubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='sectionsubject',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='Section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Section07', to='Beezaccs.section'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='kgclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes07', to='Beezaccs.classes'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='kgsubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject07', to='Beezaccs.kin_categoriesclass'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='midclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes09', to='Beezaccs.mid_classes'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='midsubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject09', to='Beezaccs.mid_subject'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='prclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Classes08', to='Beezaccs.pr_classes'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='prsubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject08', to='Beezaccs.pr_subject'),
        ),
        migrations.DeleteModel(
            name='SectionClassSubject',
        ),
        migrations.DeleteModel(
            name='StudentSectionClassSubject',
        ),
    ]
