# Generated by Django 3.1.3 on 2021-07-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0023_sctionclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=190, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=190, null=True, unique=True),
        ),
    ]
