# Generated by Django 3.1.3 on 2021-07-12 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Beezaccs', '0024_auto_20210710_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User11', to=settings.AUTH_USER_MODEL)),
                ('Student_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User12', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SctionClass',
        ),
    ]
