# Generated by Django 3.1.3 on 2021-07-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0025_auto_20210712_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='kin_exercisesonline',
            name='explanation',
            field=models.CharField(default='NULL', max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='pr_exercisesonline',
            name='explanation',
            field=models.CharField(default='NULL', max_length=190, null=True),
        ),
    ]
