# Generated by Django 3.1.3 on 2021-07-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0026_auto_20210715_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kin_exercisesonline',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='pr_exercisesonline',
            name='explanation',
        ),
    ]
