# Generated by Django 3.1.3 on 2021-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beezaccs', '0027_auto_20210715_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='kin_exercisesonline',
            name='explanation',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='pr_exercisesonline',
            name='explanation',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
